spring.datasource.url=jdbc:postgresql://localhost:5432/benefitshub
spring.datasource.username=postgres
spring.datasource.password=NewHaven2887!


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=3f8b2c1a9d7e4f6b0a2c5e8d1f3b7a9c2e4f6b8d0a2c4e6f8b0d2a4c6e8f0b2d
app.jwt.expiration=86400000